CREATE TABLE [dbo].[BOOKINGS] (
    [ID]       INT            IDENTITY (1, 1) NOT NULL,
    [NAME]     NVARCHAR (MAX) NULL,
    [PHONE]    NVARCHAR (MAX) NULL,
    [QUANTITY] INT            NOT NULL,
    [SLOT_ID]  INT            NOT NULL,
    [EMAIL]    NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_BOOKINGS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_BOOKINGS_SLOTS_SLOT_ID] FOREIGN KEY ([SLOT_ID]) REFERENCES [dbo].[SLOTS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_BOOKINGS_SLOT_ID]
    ON [dbo].[BOOKINGS]([SLOT_ID] ASC);

