CREATE TABLE [dbo].[MEDIAS] (
    [ID]       INT             IDENTITY (1, 1) NOT NULL,
    [EVENT_ID] INT             NOT NULL,
    [IMAGE]    VARBINARY (MAX) NULL,
    [URL]      NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_MEDIAS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MEDIAS_EVENTS_EVENT_ID] FOREIGN KEY ([EVENT_ID]) REFERENCES [dbo].[EVENTS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_MEDIAS_EVENT_ID]
    ON [dbo].[MEDIAS]([EVENT_ID] ASC);

