CREATE TABLE [dbo].[MENUS] (
    [ID]     INT             IDENTITY (1, 1) NOT NULL,
    [BANNER] VARBINARY (MAX) NULL,
    [NAME]   NVARCHAR (MAX)  NULL,
    [PDF]    VARBINARY (MAX) NULL,
    CONSTRAINT [PK_MENUS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

