CREATE TABLE [dbo].[MENU_ITEMS] (
    [ID]          INT             IDENTITY (1, 1) NOT NULL,
    [DESCRIPTION] NVARCHAR (MAX)  NULL,
    [IMAGE]       VARBINARY (MAX) NULL,
    [MENU_ID]     INT             NOT NULL,
    [NAME]        NVARCHAR (MAX)  NULL,
    [PRICE]       FLOAT (53)      NOT NULL,
    [IS_SPECIAL]  BIT             DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_MENU_ITEMS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MENU_ITEMS_MENUS_MENU_ID] FOREIGN KEY ([MENU_ID]) REFERENCES [dbo].[MENUS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_MENU_ITEMS_MENU_ID]
    ON [dbo].[MENU_ITEMS]([MENU_ID] ASC);

